[package]
name = "test_bevywebapp"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.2"
pollster = "1.0.1"
rav1d = { git = "https://github.com/memorysafety/rav1d.git" }
wgpu = "30.0.1"
winit = "0.30.13"
rodio = "0.22.2"
rayon = "1.12.0"
opus-rs = "0.1.32"

[dependencies.symphonia]
version = "0.6.1"
default-features = false
features = ["mkv"]

[profile.dev.package.opus-rs]
opt-level = 3

[profile.dev.package.rav1d]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1
panic = "abort"